[package]
name = "fuzon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
lazy_static = "1.5.0"
oxrdf = "0.1.7"
oxttl = "0.1.0-rc.1"
rff = "0.3.0"
